# Change these first
owner: YangHumKwan # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Public Website
    url: https://yanghumkwan.pt
  - name: Isna API
    url: https://isna.yanghumkwan.pt/api/v1/health/check

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.yanghumkwan.pt
  # baseUrl: /your-repo-name
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://github.com/YangHumKwan/upptime/raw/master/assets/aphyhk.png
  theme: night
  name: Upptime
  introTitle: "Monitoring"
  introMessage: "This tool allows uses **real-time** data to check **Associação Portuguesa de Hapkido Yang Hum Kwan**'s services."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://yanghumkwan.pt
    

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
